services:
  - type: web
    name: telegram-file-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: LINKSHORTIFY_API_KEY
        sync: false
      - key: STORAGE_CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /